export default function Footer() {
  return (
    <footer className="bg-[#0C2340] border-t border-[#FDD023]/20 text-white mt-auto">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid md:grid-cols-3 gap-8">
          <div>
            <h3 className="font-bold text-[#FDD023] mb-3">SessionSource - Louisiana</h3>
            <p className="text-sm text-blue-200">
              Making Louisiana state legislation accessible to all citizens through AI-powered summaries.
            </p>
          </div>
          
          <div>
            <h4 className="font-semibold text-[#FDD023] mb-3">Quick Links</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="/" className="text-blue-200 hover:text-[#FDD023] transition-colors">
                  All Bills
                </a>
              </li>
              <li>
                <a href="/legislators" className="text-blue-200 hover:text-[#FDD023] transition-colors">
                  Legislators
                </a>
              </li>
              <li>
                <a href="/about" className="text-blue-200 hover:text-[#FDD023] transition-colors">
                  About
                </a>
              </li>
            </ul>
          </div>
          
          <div>
            <h4 className="font-semibold text-[#FDD023] mb-3">Official Resources</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a 
                  href="https://legis.la.gov" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-blue-200 hover:text-[#FDD023] transition-colors"
                >
                  LA State Legislature
                </a>
              </li>
              <li>
                <a 
                  href="https://house.louisiana.gov" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-blue-200 hover:text-[#FDD023] transition-colors"
                >
                  LA House of Representatives
                </a>
              </li>
              <li>
                <a 
                  href="https://senate.la.gov" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-blue-200 hover:text-[#FDD023] transition-colors"
                >
                  LA Senate
                </a>
              </li>
            </ul>
          </div>
        </div>
        
        <div className="border-t border-[#FDD023]/20 mt-8 pt-8 text-sm text-center text-blue-200">
          <p>&copy; 2026 SessionSource - Louisiana. Data sourced from LegiScan. AI summaries generated by Claude AI.</p>
          <p className="mt-2 text-xs">
            Not affiliated with the Louisiana State Legislature. For official information, visit legis.la.gov
          </p>
        </div>
      </div>
    </footer>
  )
}