// lib/disclaimer.ts
// Single source of truth for all legal disclaimer text on SessionSource Louisiana.
// Import from here — never hardcode disclaimer text elsewhere in the codebase.

export const DISCLAIMER_SHORT =
  "SessionSource is an independent tracking tool not affiliated " +
  "with the Louisiana Legislature. Information may be incomplete, " +
  "delayed, or inconsistent with official records maintained by " +
  "the Louisiana Legislature. Always verify legislative data at " +
  "legis.la.gov. SessionSource does not warrant the accuracy or " +
  "completeness of any information presented."

export const DISCLAIMER_LONG =
  "SessionSource Louisiana is an independent, non-governmental " +
  "legislative tracking tool not affiliated with the Louisiana " +
  "Legislature or any governmental authority. Information " +
  "presented on this platform, including bill status, legislative " +
  "history, hearing schedules, and summaries, is sourced from " +
  "third-party data providers and may be incomplete, delayed, or " +
  "inconsistent with official records maintained by the Louisiana " +
  "Legislature. SessionSource makes no representation or warranty, " +
  "express or implied, as to the accuracy, completeness, or " +
  "timeliness of any information presented. Users should " +
  "independently verify all legislative information through " +
  "official sources, including the Louisiana Legislature's " +
  "official website at legis.la.gov. Nothing on this platform " +
  "constitutes legal advice."

export const DISCLAIMER_PDF_FOOTER =
  "SessionSource does not warrant accuracy or completeness. " +
  "Verify all information at legis.la.gov before relying on it."

export const DISCLAIMER_PDF_LEGAL_NOTICE_SUFFIX =
  "This document was generated by SessionSource Louisiana, " +
  "an independent legislative tracking platform. " +
  "Not an official government document."

export const LEGIS_URL = "https://legis.la.gov"
